routes/web.php
<?php
#-------------------------------------
#RUTAS PUBLICAS
#-------------------------------------
Auth::routes(['verify' => true]);

Route::get('/cleareverything', function () {
    $clearcache = Artisan::call('cache:clear');
    echo "Cache cleared<br>";

    $clearview = Artisan::call('view:clear');
    echo "View cleared<br>";

    $clearconfig = Artisan::call('config:cache');
    echo "Config cleared<br>";

//    $cleardebugbar = Artisan::call('debugbar:clear');
    //  echo "Debug Bar cleared<br>";
});

#Login y Deslogueo
Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login.post');
Route::post('login', 'Auth\LoginController@login')->name('login.post');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('logout', 'Auth\LoginController@logout');

#Registro de Usuario
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

# Password Reset
Route::get('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
Route::get('password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
Route::post('password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);

#Socialite o Socialogin
Route::get('login/facebook', 'SocialiteController@redirectToProvider')->name('login.facebook');
Route::get('login/facebook/callback', 'SocialiteController@handleProviderCallback');

Route::get('login/twitter', 'SocialiteController@redirectToTwitterProvider')->name('login.twitter');
Route::get('login/twitter/callback', 'SocialiteController@handleTwitterProviderCallback');

Route::get('login/google', 'SocialiteController@redirectToGoogleProvider')->name('login.google');
Route::get('login/google/callback', 'SocialiteController@handleGoogleProviderCallback');

//Rutas del front
Route::get('/somos', 'SomosController@index')->name('somos');

Route::get('/politicas-privacidad/', function () {
    return view('front.politicas-privacidad');
})->name('politicas-privacidad');

Route::get('/faq/', function () {
    return view('front.faq');
})->name('faq');

Route::get('/contacto/', function () {
    return view('front.contacto');
})->name('contacto');

Route::get('/surcusales/', function () {
    return view('front.surcusales');
})->name('surcusales');

Route::get('/servicios/', function () {
    return view('front.servicios');
})->name('servicios');

Route::get('/includes/rastrear/', function () {
    return view('front.rastrear');
})->name('rastrear');

Route::get('/calculadora/', function () {
    return view('front.calculadora');
})->name('calculadora');

Route::get('/directorio/', function () {
    return view('front.directorio');
})->name('directorio');

#Geografico
Route::get('searchState/{pais_id}', 'EstadoController@searchState')->name('searchState');
Route::get('searchCity/{estado_id}', 'CiudadController@searchCity')->name('searchCity');

#Multilenguaje
Route::get('/lang/{locale?}', 'Auth\LoginController@changeLang')->name('lang');

#--------------------------------------------------------------------------------------
#RUTAS PROTEGIDAS POR LA AUTENTICACION Y VERIFICACION DE EMAIL AL MOMENTO DEL REGISTRO
#--------------------------------------------------------------------------------------

Route::group(['middleware' => array('auth', 'verified')], function () {

    //Rutas soporte
    Route::get('/soporte', 'HomeController@soporte')->name('soporte');

    //Rutas de la plantilla
    Route::get('/dashboard', 'HomeController@dashboard')->name('home-one');
    Route::get('/home-two', 'HomeController@homeTwo')->name('home-two');
    Route::get('/stripe', 'HomeController@stripe')->name('stripe');

    #Rutas del Perfil
    Route::get('/perfil', 'HomeController@perfil')->name('perfil');
    Route::post('/storeperfil', 'HomeController@storeperfil')->name('storeperfil');
    Route::post('/fotoPerfil', 'HomeController@fotoPerfil')->name('fotoPerfil');

    //Rutas de prealertas
    Route::get('/pre-alertas', 'PrealertaController@index')->name('pre-alertas');
    Route::get('/pre-alertas/mostrar/{id}', 'PrealertaController@mostrar')->name('prealertas-mostrar');
    Route::post('/pagostripe/{amount}', 'PaymentController@pagoStripe');
    Route::post('/pagostripepromo/{amount}', 'PaymentController@pagoStripePromo');
    Route::post('/cobro', 'StripeController@cobro');

    Route::post('/pagoenviopromo', 'PaymentController@pagoEnvioPromo')->name('pagoenviopromo');

    //Rutas de direcciones
    Route::get('/direcciones', function () {
        return view('direcciones.index');
    })->name('direcciones');

    //Rutas de Servicios Adicionales
    Route::get('/servicioadicional', function () {
        return view('servicioadicional.index');
    })->name('servicioadicional');

    //rutas de ordenes
    Route::get('/ordenes', 'OrderController@index')->name('ordenes');
    Route::get('/ordenes/mostrar/{id}', 'OrderController@mostrar')->name('ordenes-mostrar');
    Route::get('/ordenes/buscar', 'OrderController@buscar')->name('ordenes-buscar');

    //Rutas de programar envios
    Route::get('programar-envios', 'OrderController@programar')->name('programar-envios');
    Route::get('programar-ver', 'OrderController@ver')->name('programar-ver');

    Route::view('/checkoutfinish', 'checkout-finish');
    Route::view('/checkoutfinishe', 'checkout-finishe');
    Route::view('/checkoutfinishpromo', 'checkout-finishpromo');
    Route::get('/checkout/{usd}', 'PaymentController@checkout')->name('checkout');
    Route::post('/checkout', 'PaymentController@createPayment')->name('create-payment');
    Route::post('/checkoutpromo', 'PaymentController@createPaymentPromo')->name('create-payment-promo');
    Route::get('/confirm', 'PaymentController@confirmPayment')->name('confirm-payment');
    Route::get('/confirmpromo', 'PaymentController@confirmPaymentpromo')->name('confirm-payment-promo');

    //Rutas de promoción
    Route::get('/promocion', 'HomeController@promocion')->name('promocion');

    //Rutas guia
    Route::get('/guia', 'GuiaController@index')->name('guia');

    //Rutas FacturacionDHL
    Route::get('/facturaciondhl', 'HomeController@facturaciondhl')->name('facturaciondhl');
    Route::get('/facturacioncomun', 'HomeController@facturacioncomun')->name('facturacioncomun');

    ##############
    # HOMEOPATIA #
    ##############

    #Roles
    Route::resource('roles', 'RoleController');

    #Menus
    Route::resource('menus', 'MenuController');

    #Permisos
    Route::resource('permissions', 'PermissionController');

    #Users
    Route::resource('users', 'UserController');
    Route::post('users/{user}', 'UserController@cambioClave')->name('users.cambioClave');

    #Medicamentos
    Route::resource('medicamentos', 'MedicamentoController');

    #Estudios Medicos
    Route::resource('estudios', 'EstudiosController');

//    Route::get('estudios/search', 'EstudiosController@index')->name('estudios.index');

    Route::get('search', 'EstudiosController@index')->name('estudios.search');

    Route::post('estudios/search', 'EstudiosController@index')->name('estudios.index');
    //Route::get('estudioPDF/{estudios}/{remedios}/{clave}/{pregnancia}/{vegetal}/{mineral}/{animal}', 'EstudiosController@estudioPDF')->name('estudios.estudioPDF');
    Route::get('estudioPDF/{estudios}/{clave}/{pregnancia}/{vegetal}/{mineral}/{animal}/{sac}/{alfabeto}/{reino}/{lang}', 'EstudiosController@estudioPDF')->name('estudios.estudioPDF');

    Route::get('estudios/create/{type}', 'EstudiosController@create')->name('estudio-create');

    #CRemedios
    Route::resource('cremedios', 'CremediosController');

    #Remedios
    Route::resource('remedios', 'RemediosController');
    Route::get('searchRemedio/{remedio_id}', 'RemediosController@searchRemedio')->name('searchRemedio');

    #Creditos
    Route::resource('creditos', 'CreditosController');
    Route::get('creditosConsolidado', 'CreditosController@consolidado')->name('creditos.consolidado');
    Route::get('creditos', 'CreditosController@index')->name('creditos.index');
    Route::post('promociones', 'CreditosController@promociones')->name('creditos.promociones');
    Route::get('promociones', 'CreditosController@promociones')->name('creditos.pricing');
    Route::get('abonar/{cliente_id}', 'CreditosController@abonar')->name('creditos.abonar');

    #Paypal
    Route::get('payment/{pricing_id}', 'PaypalController@postPayment')->name('payment');
    Route::get('payment/status/{pricing_id}', 'PaypalController@getPaymentStatus')->name('payment.status');
    Route::get('pagado/{credito_id}', 'PaypalController@pagado')->name('pagado');

    #Sobre el Calculo del Analisis del Estudio Medico
    Route::post('calcularAnalisisC', 'EstudiosController@calcularAnalisisC')->name('calcularAnalisisC');
    Route::post('calcularAnalisis', 'EstudiosController@calcularAnalisis')->name('calcularAnalisis');
    Route::post('guardarNota', 'EstudiosController@guardarNota')->name('guardarNota');
});

//Route::group(['middleware' => 'admin'], function () {
//    //Rutas para los usuarios
//    Route::get('/usuarios', 'UsuariosController@index')->name('usuarios');
//    Route::get('/listado-ordenes', 'OrderController@list')->name('listado-ordenes');
//    Route::get('/promociones', function () {
//        return view('promocion.index');
//    })->name('promociones');
//
//});

Route::resource('estudiosRemedios', 'EstudiosRemediosController');

Route::resource('estudiosRemedios', 'EstudiosRemediosController');

Route::resource('clientesCreditos', 'ClientesCreditosController');

app/Creditos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Creditos extends Model
{
    protected $table = "clientes_creditos";

    protected $fillable = [
        'cliente_id',
        'pricing_id',
        'cantidad',
        'tipo',
        'costo',
        'fecha',
        'operacion',
        'json'
    ];

//    public function cliente(){
//        return $this->belongsTo('App\Clientes', 'cliente_id');
//    }

    public function cliente(){
        return $this->belongsTo('\App\User', 'cliente_id', 'id_cliente');
    }
}

app/Http/Controllers/CreditosController.php
<?php

namespace App\Http\Controllers;

use App\Creditos;
use App\Pricing;
use Caffeinated\Shinobi\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CreditosController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        //$creditos = Creditos::where('id', 1)->get();
//        $creditos = Creditos::whereNotNull('cliente_id')->get();
        $creditos = Creditos::all();
        return view('creditos.index', compact(['creditos']));
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function consolidado()
    {
        $creditos = DB::select(
            "SELECT cliente_id, SUM(cantidad) as cantidad FROM clientes_creditos GROUP BY cliente_id; "
        );
        return view('creditos.index_consolidado', compact(['creditos']));
    }

    public function store(Request $request)
    {

        $cantidad = $request->input('cantidad');
        $id_cliente = $request->input('cliente_id');

        Creditos::create([
            'cliente_id' => $id_cliente,
            'cantidad' => intval($cantidad),
            'tipo' => 'Credito',
            'fecha' => date("Y-m-d")
        ]);

        return redirect()->route('users.index')
            ->with('info','Abono de '.$cantidad.' Créditos realizado satisfactoriamente.');
    }

    public function pricing()
    {
        $promocion = Pricing::where('promocion','=','1')->first();
        $princings = Pricing::where('promocion','!=','1')->get();
        $sincard = 1;

        return view('creditos.promociones', compact('promocion', 'princings', 'sincard'));
    }

    public function promociones()
    {
        $promocion = Pricing::where('promocion','=','1')->first();
        $princings = Pricing::where('promocion','!=','1')->get();
        $sincard = 1;

        return view('creditos.promociones', compact('promocion', 'princings', 'sincard'));
    }

    public function abonar($cliente_id)
    {
        return view('creditos.create', compact('cliente_id'));
    }

    public function show($id)
    {
        $clientesCreditos = Creditos::where('id', $id)->firts();

        if (empty($clientesCreditos)) {
            Flash::error('Clientes Creditos not found');

            return redirect(route('clientesCreditos.index'));
        }

        return view('clientes_creditos.show')->with('clientesCreditos', $clientesCreditos);
    }

}

resources/views/creditos/create.blade.php
@extends('templates.material.main')
@section('jquery') {{-- Including this section to override it empty. Using jQuery from webpack build --}} @endsection
@push('before-scripts')
    <script src="{{ mix('/js/home-one.js') }}"></script>
@endpush
@section('nombre_modulo', 'Abonar Creditos')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{route('home-one')}}">{{ _i('Inicio') }}</a></li>
    <li class="breadcrumb-item"><a href="{{route('users.index')}}">{{ _i('Usuarios') }}</a></li>
    <li class="breadcrumb-item active">Abonar Creditos</li>
@endsection
@section('content')

    <section class="content-header">
        <h1>
            Abonar Créditos
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        @if(session('info'))
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="alert alert-success text-center">{{session('info')}}</div>
                    </div>
                </div>
            </div>
        @endif
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'creditos.store', 'style'=>'width: 100%']) !!}
                    @include('creditos.partials.form')
                    <hr>
                    <a href="{{ URL::previous() }}" class="btn btn-outline-secondary float-right">{{_i('Regresar')}}</a>
                    {{ Form::submit('Abonar', ['class' => 'btn btn-outline-success float-right mr-1'])}}

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/creditos/edit.blade.php
@extends('templates.material.main')
@section('jquery') {{-- Including this section to override it empty. Using jQuery from webpack build --}} @endsection
@push('before-scripts')
    <script src="{{ mix('/js/home-one.js') }}"></script>
@endpush
@section('content')
    <section class="content-header">
        <h1>
            Actualizar créditos
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">

                   {!! Form::model($clientesCreditos, ['route' => ['clientesCreditos.update', $clientesCreditos->id], 'method' => 'patch']) !!}

                        @include('creditos.fields')

                   {!! Form::close() !!}

               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/creditos/fields.blade.php
<!-- Cliente Id Field -->
{{--<div class="form-group col-sm-6">--}}
{{--    {!! Form::label('cliente_id', 'Cliente Id:') !!}--}}
{{--    {!! Form::number('cliente_id', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Pricing Id Field -->
{{--<div class="form-group col-sm-6">--}}
{{--    {!! Form::label('pricing_id', 'Pricing Id:') !!}--}}
{{--    {!! Form::number('pricing_id', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Cantidad Field -->
<div class="row">
    <div class="form-group col-sm-12 col-lg-12">
        {!! Form::label('cantidad', 'Cantidad:') !!}
        {!! Form::number('cantidad', null, ['class' => 'form-control']) !!}
    </div>
    <div class="form-group col-sm-12 col-lg-12">
        {!! Form::label('fecha', 'Fecha:') !!}
        {!! Form::date('fecha', null, ['class' => 'form-control','id'=>'fecha']) !!}
    </div>
</div>
{{--<!-- Tipo Field -->--}}
{{--<div class="form-group col-sm-6">--}}
{{--    {!! Form::label('tipo', 'Tipo:') !!}--}}
{{--    {!! Form::text('tipo', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Costo Field -->
{{--<div class="form-group col-sm-6">--}}
{{--    {!! Form::label('costo', 'Costo:') !!}--}}
{{--    {!! Form::number('costo', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Fecha Field -->


@push('scripts')
    <script type="text/javascript">
        $('#fecha').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: false
        })
    </script>
@endpush

<!-- Operacion Field -->
{{--<div class="form-group col-sm-6">--}}
{{--    {!! Form::label('operacion', 'Operacion:') !!}--}}
{{--    {!! Form::text('operacion', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Json Field -->
{{--<div class="form-group col-sm-12 col-lg-12">--}}
{{--    {!! Form::label('json', 'Json:') !!}--}}
{{--    {!! Form::textarea('json', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Actualizar', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('creditos.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/creditos/index.blade.php
<?php //die("llegaste aqui vista"); ?>
@extends('templates.material.main')
@section('jquery') {{-- Including this section to override it empty. Using jQuery from webpack build --}} @endsection
@push('before-scripts')
    <script src="{{ mix('/js/home-one.js') }}"></script>
@endpush
@section('css')

    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/dropzone.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">
    <link rel="stylesheet" href="/vendor/wrappixel/material-pro/4.2.1/assets/plugins/toast-master/css/jquery.toast.css">

@endsection
@section('nombre_modulo', 'Créditos')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{route('home-one')}}">{{ _i('Inicio') }}</a></li>
    <li class="breadcrumb-item active"><a href="{{route('estudios.index')}}">Estudios</a></li>
@endsection
@section('content')
    <section class="content-header">
        <h1 class="pull-left">
            Créditos de Clientes
            @can('creditos.create')
                <a href="{{route('creditos.create')}}" class="btn btn-outline-success float-right"> <i class="fas fa-plus"></i> {{ _i('Crear') }}</a>
            @endcan
        </h1>
    </section>
    <div class="content">

        @include('flash::message')

        <div class="box box-primary">
            <div class="box-body">
                @include('creditos.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

@section('js')
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/locale/es.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/js/bootstrap-material-datetimepicker.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/dropzone.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        $(document).ready(function() {
            $('#data-table').DataTable({
                "order": [[ 0, "desc" ]],
                "language":{
                    "sProcessing":     "Procesando...",
                    "sLengthMenu":     "Ver _MENU_",
                    "sZeroRecords":    "No se encontraron resultados",
                    "sEmptyTable":     "Ningún dato disponible en esta tabla",
                    "sInfo":           "_START_ al _END_ de  _TOTAL_ registros",
                    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix":    "",
                    "sSearch":         "Buscar:",
                    "sUrl":            "",
                    "sInfoThousands":  ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst":    "Primero",
                        "sLast":     ">>",
                        "sNext":     ">",
                        "sPrevious": "<"
                    },
                    "oAria": {
                        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
                "pageLength": 10,
                "bDestroy": true
            });
        } );
    </script>

@endsection

resources/views/creditos/pagado.blade.php
@extends('templates.material.main')
@section('jquery') {{-- Including this section to override it empty. Using jQuery from webpack build --}} @endsection
@push('before-scripts')
    <script src="{{ mix('/js/home-one.js') }}"></script>
@endpush
@section('nombre_modulo', 'Crédito Abonado')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{route('home-one')}}">{{ _i('Inicio') }}</a></li>
    <li class="breadcrumb-item"><a href="{{route('creditos.pricing')}}">{{ _i('Obtenga su Abono') }}</a></li>
    <li class="breadcrumb-item active">{{ _i('Crédito Abonado') }}</li>
@endsection
@section('content')
    <div class="content">

        <div class="box box-primary">

            @if(session('message'))
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="alert alert-success text-center">{{session('message')}}</div>
                        </div>
                    </div>
                </div>
            @endif

            <div class="card-body">
                <div class="row">
                    <div class="col-sm-4 offset-lg-4">
                        <div class="card">
                            <div class="card-body pricing-body pl-4 pr-4 text-center">
                                <i class="far fa-check-circle fa-5x text-success"></i>
                                <h2 class="text-center">{{$credito->cantidad}}</h2>
                                <p class="text-center">
                                    @if ($credito->cantidad>1)
                                        {{ _i('Créditos Abonados') }}
                                    @else
                                        {{ _i('Crédito Abonado') }}
                                    @endif
                                </p>
                                <div class="price-table-content text-center">
                                    <div class="price-row"><h4>US$ {{number_format($credito->costo,0,'','.')}}</h4></div>
                                    <div class="price-row">{{ _i('Operación') }}: <h5>{{$credito->operacion}}</h5></div>
                                    <div class="price-row">
                                        @if (Auth::user()->creditos->sum('cantidad')>0)
                                            <a href="{{route('estudios.create')}}" class="btn btn-success">
                                                {{ _i('Crear un Nuevo Estudio Médico') }}
                                            </a>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/creditos/show.blade.php
@extends('templates.material.main')
@section('jquery') {{-- Including this section to override it empty. Using jQuery from webpack build --}} @endsection
@push('before-scripts')
    <script src="{{ mix('/js/home-one.js') }}"></script>
@endpush
@section('nombre_modulo', 'Abonar Creditos')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{route('home-one')}}">{{ _i('Inicio') }}</a></li>
    <li class="breadcrumb-item"><a href="{{route('users.index')}}">{{ _i('Usuarios') }}</a></li>
    <li class="breadcrumb-item active">Detalle del Creditos</li>
@endsection
@section('content')
    <section class="content-header">
        <h1>
            Clientes Creditos
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
{{--                    @include('clientes_creditos.show_fields')--}}
{{--                    <a href="{{ route('clientesCreditos.index') }}" class="btn btn-default">Back</a>--}}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/creditos/table.blade.php
<table style="" id="data-table" class="table table-striped table-bordered dt-responsive nowrap">
    <thead>
        <tr>
            <th style="width: 20%">Cliente</th>
            <th style="width: 20%">Correo</th>
            <th style="width: 20%">Cantidad</th>
            <th style="width: 20%">Última fecha de registro</th>
            <th style="width: 20%">Acción</th>
        </tr>
    </thead>
    <tbody>
    @foreach($creditos as $clientesCreditos)
        <tr>
        <td>{{ $clientesCreditos->cliente->nombre }}</td>
        <td>{{ $clientesCreditos->cliente->email }}</td>
        <td>{{ $clientesCreditos->cantidad }}</td>
        <td>{{ $clientesCreditos->fecha }}</td>
        <td>
            <a href="{{route('clientesCreditos.edit', $clientesCreditos->id)}}" class="btn btn-outline-success btn-round btn-sm">
                <i class="fas fa-pencil-alt"></i>
            </a>
        </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/creditos/table_consolidado.blade.php
<table style="" id="data-table" class="table table-striped table-bordered nowrap">
    <thead>
        <tr>
            <th style="width: 33%">Cliente</th>
            <th style="width: 33%">Correo</th>
            <th style="width: 33%">Cantidad</th>
        </tr>
    </thead>
    <tbody>
    @foreach($creditos as $clientesCreditos)
        <?php
        $cliente = \App\Http\Controllers\UserController::getClient($clientesCreditos->cliente_id)
        ?>
        @php
            if(isset($cliente)) {
            @endphp
                <tr>
                    <td>{{ $cliente->nombre }}</td>
                    <td>{{ $cliente->email }}</td>
                    <td>{{ $clientesCreditos->cantidad }}</td>
                </tr>
            @php
            }
        @endphp
    @endforeach
    </tbody>
</table>

resources/views/creditos/table_consolidado_20200609.blade.php
<table style="" id="data-table" class="table table-striped table-bordered nowrap">
    <thead>
        <tr>
            <th style="width: 33%">Cliente</th>
            <th style="width: 33%">Correo</th>
            <th style="width: 33%">Cantidad</th>
        </tr>
    </thead>
    <tbody>
    @foreach($creditos as $clientesCreditos)
        <?php $cliente = \App\Http\Controllers\UserController::getClient($clientesCreditos->cliente_id) ?>
        <tr>
        <td>{{ $cliente->nombre }}</td>
        <td>{{ $cliente->email }}</td>
        <td>{{ $clientesCreditos->cantidad }}</td>
        </tr>
    @endforeach
    </tbody>
</table>